### ISSUE TITLE
[[Enumerate]] is being removed

### ISSUE THREAD

**Issue by leobalter** [tc39/proposal-object-values-entries#12]
[[Enumerate]] is being removed on ecma262 and it affects this proposal:

Refs:
- https://github.com/tc39/proposal-object-values-entries/blob/master/spec.emu#L63
- https://github.com/tc39/ecma262/pull/367

It may easily replaced by the new `EnumerateObjectProperties` abstract operation.

cc @bterlson

**Comment by ljharb** [comment]
Thanks, will update. ([chakra pr](https://github.com/Microsoft/ChakraCore/issues/274))
