### ISSUE TITLE
Reflect is not defined in Safari <= 9

### ISSUE THREAD

**Issue by callmeaponte** [tc39/proposal-object-values-entries#19]
I wanted to use this polyfill in order to support mobile Safari users, but it throws a reference error since the global Reflect object does not exist in mobile Safari (version 9 and lower).

Is there any way you can provide a version that does not use Reflect?

**Comment by ljharb** [comment]
Yes - the polyfill from the proposal repo shouldn't be used.

The readme links to https://github.com/es-shims/Object.values and https://github.com/es-shims/Object.entries, which are proper polyfills published to npm.
