### ISSUE TITLE
Why use Function.bind.call in polyfill?

### ISSUE THREAD

**Issue by KoretskyiBohdan** [tc39/proposal-object-values-entries#20]
#### Why do you use Function.bind.call(Function.call, Array.prototype.concat) instead of Array.prototype.concat?
It works the same but looks a little bit confused:

```javascript 
Function.bind.call(Function.call, Array.prototype.concat)([1,2,3,4], [1,2,3,4], [1,2,3,4])
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
Array.prototype.concat([1,2,3,4], [1,2,3,4], [1,2,3,4])
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
```

**Comment by ljharb** [comment]
Because somebody might later `delete Array.prototype.concat` (or replace it with some other function), and your version would break in that case - mine would not.
