### ISSUE TITLE
Reflect isn't in older browsers... Not a good polyfill

### ISSUE THREAD

**Issue by intervalia** [tc39/proposal-object-values-entries#21]
In this file: https://github.com/tc39/proposal-object-values-entries/blob/master/polyfill.js

You are using Reflect and that isn't available in browsers that need this polyfill. Is there a way to write the polyfill without using Reflect so we can use this in earlier browsers?

**Comment by ljharb** [comment]
Polyfills in proposal repos aren’t meant for production use. Use https://github.com/es-shims/Object.values, which is linked from the header in the readme.
