### ISSUE TITLE
Function length

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-object-values-entries#7]
I don't think it's necessary to list the length of functions. The specification already indicates that if arguments are written in the spec syntactically, then the number of non-bracketed arguments is the length. If you do include the length, it should be normative change, not a note.

**Comment by ljharb** [comment]
I've filed bugs in the past about a missing length and had them added, even though there's a tiny note buried in the spec that says what you describe.

I've often seen implementations screw up the length. I'd prefer it if the spec always, without exception, listed the length of every function alongside it. @bterlson: what are your thoughts here?

**Comment by bterlson** [comment]
I'm ok omitting length, but I'll leave it up to you. Browsers have messed up length of sections that include an explicit length so I'm not sure making it more explicit prevents the issue :)

But if you want to include it, it doesn't belong in a note.

**Comment by ljharb** [comment]
Gotcha, I was confused about normative vs non-normative, and what constitutes what. The understanding I now have is that it's required unless it says "Note:" in which case it's non-normative - assuming that's correct I'll update and close.

**Comment by bterlson** [comment]
You could make an argument for a note as it's clarifying what was previously stated so a normative requirement isn't necessary, however since other clauses defining built-in functions contain normative length we should probably continue the trend.
