### ISSUE TITLE
Spec text reviewer signoff?

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-object-values-entries#8]
It appears all the outstanding spec text issues have been resolved.

@wycats @littledan @rwaldron - as the designated reviewers (thanks for volunteering!), are there any other issues blocking official signoff? If so, please file them! If not, please indicate as such here :-)

**Comment by littledan** [comment]
You have my signoff.

**Comment by rwaldron** [comment]
LGTM!

**Comment by wycats** [comment]
:+1;

**Comment by wycats** [comment]
:+1:

**Comment by ljharb** [comment]
Thanks, folks!
